[MOD] Components refactor
luciaiosa/react_typescript_redux_sagas_docker_axios pull request #3
Opened 2020-04-01 17:24 UTC by luciaiosa

2020-04-02 09:44 UTC, alexhoo requested changes
mejor que antes :)
pero: 
- debes refactorizar más los componentes. Si empiezas a alcanzar 200 lineas de código piensa que algo se puede refactorizar y extraer código a componentes 
- échale un vistazo a las sagas en como se usa 'call'

2020-04-02 09:44 UTC, alexhoo commented on rick_morty/src/store/characters/Sagas.ts
> +        const response = yield call(() =>
esto debería ser así:
```
const response = yield call(charactersFetch, action.payload.currentPage, action.payload.searchTerm)
```

2020-04-02 09:44 UTC, alexhoo commented on rick_morty/src/store/characters/Sagas.ts
>      const character = yield call(() => characterByIdFetch(action.payload));
lo mismo que la anterior
```
const character = yield call(characterByIdFetch, action.payload)
```

2020-04-02 15:36 UTC, luciaiosa commented on rick_morty/src/store/characters/Sagas.ts
>      const character = yield call(() => characterByIdFetch(action.payload));
Muchas gracias, ya lo he cambiado. :)

2020-04-03 07:10 UTC, alexhoo approved these changes
Buenos días te comento.
- Las PRs deben ser cortas, de lo contrario el revisor tendrá que  pasar muchisimo timepo revisando la PR y cuantó mas tiempo pase la atención al código va decreciendo. Si por ejemplo trabajas en la APi manda PR de la API, si trabajas en la sagas pues lo mismo. Es que la PR ha sido una mezcla de todo y se suele trabajar por feature branchs, por tanto si creas la feature branch 'user_saga' la PR será sobre la saga.
Con todo esto, y aún así, veo que vas avanzando muy bien ;)

2020-04-03 07:53 UTC, merged